import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/authContext";
import { NextUIProvider } from "@nextui-org/react";
import CustomNavbar from "@/components/Navbar";
import { Sidebar } from "@/components/Sidebar";
import { useState } from "react";
import { SocketProvider } from "@/context/socketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Social UTN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <SocketProvider>
            <NextUIProvider>
              {/* <CustomNavbar /> */}
              {/* <Sidebar/> */}
              <div className="main-content min-h-screen">{children}</div>
            </NextUIProvider>
          </SocketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
